[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.121.1"      # latest stable Hugo as of 2025
  NODE_VERSION = "20"           # Node 16 deprecated; use Node 20
  NETLIFY_USE_JAMMY = "true"    # use Ubuntu 22.04 build image

[context]
  [context.branch-deploy]
    command = "hugo -F -b $DEPLOY_PRIME_URL"

  [context.deploy-preview]
    command = "hugo -F -b $DEPLOY_PRIME_URL"

  [context.production]
    [context.production.environment]
      HUGO_ENV = "production"

